[package]
name = "rsedlib"
version = "0.0.2"
edition = "2021"

description = "rust binding of edlib"
license = "MIT"
repository ="https://github.com/keithyin/rsedlib"

[dependencies]
libc="0.2"

[build-dependencies]
cmake = "0.1"